apiVersion: v1
kind: Secret
metadata:
  name: mongo-root
type: Opaque
stringData:
  username: ${MONGO_INITDB_ROOT_USERNAME}
  password: ${MONGO_INITDB_ROOT_PASSWORD}
---
apiVersion: v1
kind: Secret
metadata:
  name: mongo-keyfile
type: Opaque
stringData:
  keyfile: ${MONGO_KEYFILE}
