apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: jp-mongo
build:
  artifacts:
    - image: localhost:5000/mongo
      context: .
      docker:
        dockerfile: Dockerfile
        
manifests:
  rawYaml:
    - db.yaml
