configMapGenerator:
  - name: jp-app-config
    envs:
      - config.env
secretGenerator:
  - name: jp-app-secrets
    envs:
      - secrets.env
resources:
  - ../base
  - service.yaml
namePrefix: staging-
labels:
  - pairs:
      app: staging-jp-app
    includeSelectors: true
    includeTemplates: true
