apiVersion: apps/v1
kind: Deployment
metadata:
  name: jp-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jp-app
  template:
    metadata:
      labels:
        app: jp-app
    spec:
      containers:
        - name: caddy
          image: caddy:2
          ports:
            - containerPort: 8080
          args:
            [
              "caddy",
              "run",
              "--config",
              "/etc/caddy/Caddyfile",
              "--adapter",
              "caddyfile",
            ]
          volumeMounts:
            - name: caddyfile
              mountPath: /etc/caddy/Caddyfile
              subPath: Caddyfile
              readOnly: true
          resources:
            limits:
              memory: "256Mi"
              cpu: "250m"
            requests:
              memory: "128Mi"
              cpu: "100m"
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
        - name: app
          image: tmshkr/journaling.place
          command: ["npm", "run", "start"]
          ports:
            - containerPort: 3000
            - containerPort: 3333
          envFrom:
            - configMapRef:
                name: jp-app-config
            - secretRef:
                name: jp-app-secrets
          resources:
            limits:
              memory: "1024Mi"
              cpu: "250m"
            requests:
              memory: "128Mi"
              cpu: "100m"
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
      volumes:
        - name: caddyfile
          configMap:
            name: jp-caddy-config
